sudo: required
services: 
    - docker

before_install:
    - docker build -t jlee12/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jlee12/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-321224189992"
    bucker_path: "docker-react"
    on: 
        branch: master
    access_key_id: $access_key_id
    secret_access_key:
        secure: "$secret_access_key"